Algoritmo numero_primo
	DEFINIR N, P COMO ENTERO;
	DEFINIR NP COMO LOGICO;
	NP<-VERDADERO;
	ESCRIBIR"INGRESAR PRIMER NUMERO COMO ENTERO POSITIVO";
	LEER N;
	SI N<=1 Entonces
		ESCRIBIR "INCORRECTO: EL NUMERO TIENE QUE SER MAYOR QUE EL 1";
	SiNo
		PARA P<-2 HASTA N/2 HACER
			SI N MOD P=0 Entonces
				NP<-FALSO;
			FinSi
		FinPara
		SI NP Entonces
			ESCRIBIR "EL NUMERO ",N," ES PRIMO";
	SiNo
			ESCRIBIR "EL NUMERO ",N," NO ES PRIMO";
			FinSi
	FinSi
FinAlgoritmo
